{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Obtaining dependency information for face_recognition from https://files.pythonhosted.org/packages/1e/95/f6c9330f54ab07bfa032bf3715c12455a381083125d8880c43cbe76bb3d0/face_recognition-1.3.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl.metadata (21 kB)\n",
      "Requirement already satisfied: opencv-python in c:\\users\\princ\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (4.10.0.84)\n",
      "Requirement already satisfied: numpy in c:\\users\\princ\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (1.26.4)\n",
      "Collecting face-recognition-models>=0.3.0 (from face_recognition)\n",
      "  Using cached face_recognition_models-0.3.0-py2.py3-none-any.whl\n",
      "Requirement already satisfied: Click>=6.0 in c:\\users\\princ\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from face_recognition) (8.1.7)\n",
      "Collecting dlib>=19.7 (from face_recognition)\n",
      "  Using cached dlib-19.24.6.tar.gz (3.4 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: Pillow in c:\\users\\princ\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from face_recognition) (10.2.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\princ\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from Click>=6.0->face_recognition) (0.4.4)\n",
      "Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × python setup.py bdist_wheel did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [69 lines of output]\n",
      "      running bdist_wheel\n",
      "      running build\n",
      "      running build_ext\n",
      "      C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\setup.py:163: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "        if LooseVersion(cmake_version) < '3.1.0':\n",
      "      Building extension for Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]\n",
      "      Invoking CMake setup: 'cmake C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\build\\lib.win-amd64-cpython-311 -DPYTHON_EXECUTABLE=c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\python.exe -DDLIB_USE_FFMPEG=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\build\\lib.win-amd64-cpython-311 -A x64'\n",
      "      -- Building for: NMake Makefiles\n",
      "      CMake Error at CMakeLists.txt:5 (message):\n",
      "      \n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "        You must use Visual Studio to build a python extension on windows.  If you\n",
      "        are getting this error it means you have not installed Visual C++.  Note\n",
      "        that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "        development.  You need to install Visual Studio for C++.\n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "      \n",
      "      \n",
      "      -- Configuring incomplete, errors occurred!\n",
      "      Traceback (most recent call last):\n",
      "        File \"<string>\", line 2, in <module>\n",
      "        File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "        File \"C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\setup.py\", line 243, in <module>\n",
      "          setup(\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\__init__.py\", line 108, in setup\n",
      "          return distutils.core.setup(**attrs)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 184, in setup\n",
      "          return run_commands(dist)\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 200, in run_commands\n",
      "          dist.run_commands()\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 970, in run_commands\n",
      "          self.run_command(cmd)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\dist.py\", line 945, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 989, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\command\\bdist_wheel.py\", line 373, in run\n",
      "          self.run_command(\"build\")\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 316, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\dist.py\", line 945, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 989, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 135, in run\n",
      "          self.run_command(cmd_name)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 316, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\dist.py\", line 945, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 989, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\setup.py\", line 168, in run\n",
      "          self.build_extension(ext)\n",
      "        File \"C:\\Users\\princ\\AppData\\Local\\Temp\\pip-install-s9pwwpu4\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\setup.py\", line 206, in build_extension\n",
      "          subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "        File \"c:\\Users\\princ\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\subprocess.py\", line 413, in check_call\n",
      "          raise CalledProcessError(retcode, cmd)\n",
      "      subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\princ\\\\AppData\\\\Local\\\\Temp\\\\pip-install-s9pwwpu4\\\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\princ\\\\AppData\\\\Local\\\\Temp\\\\pip-install-s9pwwpu4\\\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\\\build\\\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE=c:\\\\Users\\\\princ\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python311\\\\python.exe', '-DDLIB_USE_FFMPEG=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\princ\\\\AppData\\\\Local\\\\Temp\\\\pip-install-s9pwwpu4\\\\dlib_d9f9cba8db0f4bca8ee5084dad46f59a\\\\build\\\\lib.win-amd64-cpython-311', '-A', 'x64']' returned non-zero exit status 1.\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects\n",
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 25.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "pip install face_recognition opencv-python numpy\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import face_recognition\n",
    "import cv2\n",
    "\n",
    "def comparar_faces(imagem_referencia, imagem_teste):\n",
    "    ref_img = face_recognition.load_image_file(imagem_referencia)\n",
    "    teste_img = face_recognition.load_image_file(imagem_teste)\n",
    "    \n",
    "    ref_encodings = face_recognition.face_encodings(ref_img)\n",
    "    teste_encodings = face_recognition.face_encodings(teste_img)\n",
    "\n",
    "    if not ref_encodings:\n",
    "        return \"Nenhum rosto encontrado na imagem de referência!\"\n",
    "    if not teste_encodings:\n",
    "        return \"Nenhum rosto encontrado na imagem de teste!\"\n",
    "\n",
    "    # Comparar as faces e calcular a distância\n",
    "    resultado = face_recognition.compare_faces([ref_encodings[0]], teste_encodings[0])\n",
    "    distancia = face_recognition.face_distance([ref_encodings[0]], teste_encodings[0])\n",
    "\n",
    "    return f\"É a mesma pessoa? {resultado[0]} - Distância de Similaridade: {distancia[0]}\"\n",
    "\n",
    "imagem_referencia = \"rostojpg\" \n",
    "imagem_teste = \"pessoa2.jpg\"  \n",
    "\n",
    "resultado = comparar_faces(imagem_referencia, imagem_teste)\n",
    "print(resultado)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
